services:
  db:
    build: ./sqlserver
    ports:
      - 2320:1433
  backend:
    build: ./PRM_Project/Backend
    container_name: backend
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:8080
    depends_on:
      - db
